[package]
name = "co-auther"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokenizers = { version = "0.13.4", default-features = false }

candle-core = "0.2.1"
candle-transformers = "0.2.1"